name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '13 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://data.sccgov.org/resource/59wk-iusg.json | jq . > cases_by_city.json
        curl https://data.sccgov.org/resource/dvgc-tzgq.json | jq . > tests_by_date.json
        curl https://data.sccgov.org/resource/6cnm-gchg.json | jq . > cases_by_date.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
